name: Roverman Technical Signals

on:
  schedule:
    # 每週一、四 香港時間 9:00AM （即 UTC 01:00AM）
    - cron: '0 1 * * 1,4'
  workflow_dispatch:  # 亦可手動即時觸發

jobs:
  send-email-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install yfinance pandas

    - name: Run Technical Signal Script
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      run: |
        python send_email.py
